name: 参与者信息
description: 参加茶话会人员填写
body:
- type: input
  attributes:
    label: '你的昵称'
- type: checkboxes
  attributes: 
    label: '你的分享内容'
    options:
    - label: '技术类'
    - label: '其他'
  validations:
      required: false
