name: 参加茶话会信息填报
description: '信息填报'
title: "[茶话会参加模板]："
assigness:
  - octocat
body:
  - type: input
    id: address
    attributes:
      label: '联系方式'
      description: '请写入您的联系方式'
      placeholder: '例如qq/vx'
    validations:
      required: true
  - type: textarea
    id: abstract
    attributes:
      label: '摘要'
      description: '您的讲解的主要内容'
    validations:
      required: false
