name: 参加茶话会信息填报
description: 信息填报
title: "[茶话会参加模板]："
assignees:
  - oct
body:
  - type: input
    id: '地址'
    attributes:
      label: '联系方式'
      description: '请写入您的联系方式'
      placeholder: '例如qq/vx'
    validations:
      required: true
  - type: textarea
    id: abstract
    attributes:
      description: '您讲解的主要内容'
      label: '摘要'
    validations:
      required: false
