name: 参加茶话会信息填报
description: 信息填报
title: "[茶话会参加模板]："
assignees:
  - oct
body:
  - type: input
    id: address
    attributes:
      label: '联系方式'
      description: '请写入您的联系方式'
      placeholder: '例如qq/vx'
    validations:
      required: true
  - type: textarea
    id: abstract
    attributes:
      placeholder: 填写您的主要讲解内容
      description: 可选
      label: '摘要'
    validations:
      required: false
  - type: dropdown
    id: talk_xingshi
    attributes:
      label: '讲解形式'
      description: '通过什么方式讲解您的内容'
      options:
        - ppt
        - '演讲'
        - '其他'
    validations: 
      required: true
  - type: checkboxes
    attributes: 
      label: '关闭issue前检查内容'
      description: '报名人不需要填写'
      options:
        - label: 'ppt是否上传〈pr链接〉'
        - label: '是否有文档阅读〈链接〉'
