name: 参与者信息模板
description: 创建 Issue 时填写参与者信息
title: "[参与者信息]: "
labels: ["参与者信息"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat  # 替换为你想默认指派的用户名
body:
  - type: markdown
    attributes:
      value: |
        谢谢您花时间填写这个参与者信息模板！
  - type: input
    id: author
    attributes:
      label: '作者'
      description: '昵称/github_id/xxx'
      placeholder: '张三/github_id/xxx'
    validations:
      required: true
  - type: checkboxes
    id: content_type
    attributes:
      label: '内容形式'
      options:
        - label: '课程'
        - label: '报告'
        - label: '其他'
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: '摘要'
      description: '可选'
      placeholder: '提供内容摘要（可选）'
    validations:
      required: false
  - type: input
    id: duration
    attributes:
      label: '预计时长'
      description: '预计完成内容所需时长'
      placeholder: '例如：2小时'
    validations:
      required: true
  - type: input
    id: participation_time
    attributes:
      label: '参加时间'
      description: '请填写参加时间'
      placeholder: '例如：2024年10月25日'
    validations:
      required: true
  - type: input
    id: task_details
    attributes:
      label: '开发任务详情'
      description: '请详细描述开发任务'
      placeholder: '例如：实现登录功能'
    validations:
      required: false
  - type: input
    id: competition_info
    attributes:
      label: '比赛信息'
      description: '请填写比赛相关信息'
      placeholder: '例如：比赛名称、时间等'
    validations:
      required: false
  - type: input
    id: team_request
    attributes:
      label: '组队需求'
      description: '请填写组队要求或可加入的队伍'
      placeholder: '例如：寻找前端开发者'
    validations:
      required: false
  - type: input
    id: progress_tracking
    attributes:
      label: '进度跟踪'
      description: '请填写比赛进度或任务进展'
      placeholder: '例如：第一轮已完成'
    validations:
      required: false
  - type: checkboxes
    id: pre_close_check
    attributes:
      label: '关闭 Issue 前检查'
      options:
        - label: 'PPT 是否上传：关联到 PR 链接'
        - label: '源文件（例如 markdown 文件）是否上传'
        - label: '视频是否上传：是/否'
    validations:
      required: true
