name: 错误报告模板
description: 提交一个错误报告
title: "文件名： "
labels:
  - 文档
projects:
  - octo-org/1
  - github/2
body:
  - type: input
    id: contact
    attributes:
      label: '作者'
      description: '你的名称或 GitHub ID'
      placeholder: '张三/github_id'
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: '描述'
      description: '请描述你遇到的问题。'
      placeholder: '提供一个清晰简洁的错误描述。'
    validations:
      required: true
  - type: input
    id: steps
    attributes:
      label: '重现步骤'
      description: '列出重现错误的步骤。'
      placeholder: '1. 第一步\n2. 第二步\n3. 第三步'
    validations:
      required: true
  - type: input
    id: expected
    attributes:
      label: '预期行为'
      description: '你预期会发生什么。'
      placeholder: '解释你期望发生的情况。'
    validations:
      required: true
  - type: input
    id: actual
    attributes:
      label: '实际行为'
      description: '实际发生了什么。'
      placeholder: '解释实际发生的情况。'
    validations:
      required: true
