name: '一个名字'
description: File a bug report.
title: "文件名： "
labels:
  - '文档'
projects:
  - octo-org/1  
  - github/2                   
body: 
  - type: input          
    id: contact
    attributes:
      label: '作者'
      description: '你的名称'
      placeholder: '张三/github_id'
    validations:
      required: false  
