name: '一个名字'
description: File a bug report.
title: "文件名： "
labels:
  - 文档
projects:
  - octo-org/1
  - github/2    
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        '请参考此模板进行issue创建'
