name: Bug Report
description: Submit a bug report
title: "File Name: "
labels:
  - Documentation
projects:
  - octo-org/1
  - github/2
body:
  - type: input
    id: contact
    attributes:
      label: 'Author'
      description: 'Your name or GitHub ID'
      placeholder: 'John Doe/github_id'
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: 'Description'
      description: 'Please describe the issue you encountered.'
      placeholder: 'Provide a clear and concise description of the bug.'
    validations:
      required: true
  - type: input
    id: steps
    attributes:
      label: 'Steps to Reproduce'
      description: 'List the steps to reproduce the bug.'
      placeholder: '1. Step one\n2. Step two\n3. Step three'
    validations:
      required: true
  - type: input
    id: expected
    attributes:
      label: 'Expected Behavior'
      description: 'What you expected to happen.'
      placeholder: 'Explain what you expected to happen.'
    validations:
      required: true
  - type: input
    id: actual
    attributes:
      label: 'Actual Behavior'
      description: 'What actually happened.'
      placeholder: 'Explain what actually happened.'
    validations:
      required: true
